version: '3.9'

services:

backend:
build: .
container_name: smart_parking_backend
ports:
- "8000:8000"
depends_on:
- mongodb
- kafka
environment:
- MONGO_URL=mongodb://mongodb:27017
- DATABASE_NAME=smart_parking
- KAFKA_BOOTSTRAP_SERVERS=kafka:9092

mongodb:
image: mongo:7
container_name: smart_parking_mongodb
ports:
- "27017:27017"

zookeeper:
image: confluentinc/cp-zookeeper:7.5.0
container_name: zookeeper
environment:
ZOOKEEPER_CLIENT_PORT: 2181

kafka:
image: confluentinc/cp-kafka:7.5.0
container_name: kafka
depends_on:
- zookeeper
ports:
- "9092:9092"
environment:
KAFKA_BROKER_ID: 1
KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

consumer:
  build: .
  command: python -m services.kafka_consumer
  depends_on:
    - kafka
    - mongodb